language: node_js

cache:
  directories:
    "node_modules"

branches:
  only:
    - master

install:
    - npm install
    - npm run generate

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_ACCESS_TOKEN
  repo: yliess86/yliess86.github.io
  taget-branches: master
  local-dir: dist
  on:
    branch: master